"use client";
import type { NextPage } from "next";
import Head from "next/head";
import './estilo/Random.css'
import { MouseEventHandler, useState } from "react";
import LazyImage from "./components/LazyImage";


const random = () => Math.floor(Math.random() * 122) + 1;




//Generador de id unico
const GenerateId=()=> Math.random().toString(36).substr(2,9)


type ImageItem={id:string; url:string }
const Home: NextPage = () => {

  "use client";
   const[images, setImages]= useState <Array<ImageItem>>([]);
  
   const AddNewFox: MouseEventHandler<HTMLButtonElement>=(event)=>{
    const newImgeItem={
       id: GenerateId(), 
       url:`https://randomfox.ca/images/${random()}.jpg`,
  
    };
    setImages([
      ...images,
      newImgeItem
    ])
  }
   return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hey Platzi 😎!</h1>
        <button className="btn" onClick={AddNewFox}>Add New Fox</button>
      <p>Esta es la parte del cuerpo de la pagina web</p>
      {images.map(({id, url})=>( 
<div key={id} className="p-4">
 

      <LazyImage src={url}
          width={320}
          height='auto'
          title="Ramdow Fox"
          className="mx-auto rounded-md bg-gray-300"
          onClick={() => console.log("hey")} imagen={""}/>

   </div>  
  )  )}
      
      </main>

      <footer className="footer">Fin</footer>
    </div>
  );
};

export default Home;